-- 코드를 입력하세요
SET @HOUR = -1;

SELECT (@HOUR := @HOUR + 1) AS HOUR, 
    (SELECT COUNT(HOUR(DATETIME))
    FROM ANIMAL_OUTS
    WHERE HOUR(DATETIME) = @HOUR) AS COUNT

FROM ANIMAL_OUTS
WHERE @HOUR < 23;


# SELECT B.HOUR, COUNT(ANIMAL_ID) AS COUNT
# FROM ANIMAL_OUTS AS A
# RIGHT JOIN (SELECT ROW_NUMBER() OVER(ORDER BY ANIMAL_ID ASC) - 1 AS HOUR
#       FROM ANIMAL_OUTS
#       LIMIT 24) AS B
# ON HOUR(A.DATETIME) = B.HOUR
# GROUP BY B.HOUR;
